# Generated by Django 2.1.3 on 2019-03-21 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20190321_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.CharField(default={}, max_length=600),
            preserve_default=False,
        ),
    ]
