# Generated by Django 2.1.3 on 2019-03-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_auto_20190322_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
