# Generated by Django 2.1.3 on 2019-03-22 07:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_auto_20190322_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
