# Generated by Django 2.1.3 on 2019-03-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20190321_1755'),
        ('carts', '0014_auto_20190322_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.Products'),
        ),
    ]
