# Generated by Django 2.1.3 on 2019-03-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0015_auto_20190322_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='variations',
            field=models.TextField(default=dict),
            preserve_default=False,
        ),
    ]
