# Generated by Django 2.1.3 on 2019-03-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0016_cart_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='variations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
