# Generated by Django 2.1.3 on 2019-03-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0017_auto_20190322_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='variations',
            field=models.TextField(blank=True, default={}, null=True),
        ),
    ]
