# Generated by Django 2.1.3 on 2019-03-23 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0021_auto_20190322_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
    ]
