# Generated by Django 2.1.3 on 2019-03-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_cakevariation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CakeVariation',
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.CharField(choices=[('0.5', '½ kg'), ('1', '1 kg'), ('1.5', '1½ kg'), ('2', '2 kg'), ('2.5', '2½ kg'), ('3', '3 kg')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
