# Generated by Django 2.1.3 on 2019-07-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='options',
            field=models.BooleanField(default=False),
        ),
    ]
