# Generated by Django 2.1.3 on 2019-01-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20190104_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='full_name',
            field=models.CharField(default='abc', max_length=255),
            preserve_default=False,
        ),
    ]
