# Generated by Django 2.1.3 on 2019-02-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_emailactivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestphone',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
