# Generated by Django 2.1.3 on 2019-02-02 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_guestphone_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestphone',
            name='otp',
        ),
    ]
