# Generated by Django 2.1.3 on 2019-03-17 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-timestamp']},
        ),
    ]
