# Generated by Django 2.1.3 on 2019-03-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190317_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Paid', 'Paid'), ('Ready', 'Ready'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='created', max_length=120),
        ),
    ]
