# Generated by Django 2.1.3 on 2019-03-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190323_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Paid', 'Paid'), ('Ready', 'Ready'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Created', max_length=120),
        ),
    ]
