# Generated by Django 2.1.3 on 2019-03-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190324_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('ready', 'Ready'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='created', max_length=120),
        ),
    ]
